### ISSUE TITLE
[Failed-AutoCherryPick] - Convert CLI tests to manifester

### ISSUE THREAD

**Issue by Satellite-QE** [SatelliteQE/robottelo#10627]
#### Auto-Cherry-Pick WorkFlow Failure:
- To Branch: 6.11.z
- [Failed Cherrypick Action](https://github.com/SatelliteQE/robottelo/actions/runs/4082031217)
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/10209)

**Comment by Gauravtalreja1** [comment]
@synkd Are you planning to pull this in 6.11.z?

**Comment by synkd** [comment]
@Gauravtalreja1 yes, but doing so is currently blocked by https://github.com/SatelliteQE/robottelo/issues/10409.

**Comment by ogajduse** [comment]
Should we close this one since @shweta83 did not cherry-pick #10409 to 6.11.z yet and 6.11 is soon to be EOL?

**Comment by synkd** [comment]
@ogajduse That's a reasonable question. If @shweta83 is not planning to cherry-pick https://github.com/SatelliteQE/robottelo/issues/10409, then we can close this. However, since 6.11 does not go EOL until early next year [1], I feel that it's a bit early to close this out.

[1] https://access.redhat.com/support/policy/updates/satellite
