### ISSUE TITLE
CLI : Automate abrt scenario

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#1828]
$sleep 1d &
$kill -SEGV $!
$smart-proxy-abrt-send

**Comment by cswiii** [comment]
I assume this is mostly covered by 

https://github.com/SatelliteQE/robottelo/pull/1830

However, a few updates need to be made that immediately come to mind. Likely there could be more:

* "Assertions of Hostname is possible" -- do we mean "edit"?
* Also, we will want to assure a variety of validation tests are performed on hostname (and really, any field we can edit that is related to ABRT - username, passwd?)
* What happens if a bad hostname is entered and/or host is not responding?  Do we handle that situation gracefully (queueing reports, etc?)
* Bad Hostname
* Bad auth

**Comment by tkolhar** [comment]
sent pr covering the above new scenarios 
- https://github.com/SatelliteQE/robottelo/pull/1880

**Comment by tkolhar** [comment]
pr covered
