### ISSUE TITLE
Update UI tests for Docker repositories

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#1887]
Creating **Docker** repositories now require 2 attributes:

* Name: any random set of characters within the acceptable range supported
* Upstream Repository Name: Name of the upstream repository you want to sync. Example: 'busybox' or 'fedora/ssh;.

The **Upstream Repository Name** attribute is only required for Docker repositories.

![screenshot_2015-02-05_09_17_29](https://cloud.githubusercontent.com/assets/53362/6061780/9228cac4-ad18-11e4-8481-c02ace672881.png)

**Comment by abalakh** [comment]
Is this issue is still urgent?
Docker repos are currently used in 2 files of UI tests:
```
tests/foreman/ui/test_docker.py
tests/foreman/ui/test_repository.py
```
File ```test_docker.py``` contains only manual tests, so there's nothing to update. ```test_repository.py``` contains 3 tests with docker:
```
test_create_repo_3
test_create_repo_4
test_syncnow_custom_repos_3
```
All of them are up-to-date. Factory's ```make_repository``` is already updated to accept ```upstream_repo_name``` parameter too. Maybe this issue is outdated and can be closed?

**Comment by omaciel** [comment]
@abalakh yup, looks like you can close it :)
