### ISSUE TITLE
foreman version should not have the 'develop' tag.

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#1958]
[root@xyzabc ~]#  cat /usr/share/foreman/VERSION
    1.6-develop

assert for no develop tag in the foreman version.

**Comment by ripcurld00d** [comment]
:+1:

**Comment by elyezer** [comment]
I saw in email, this change should be made on Satellite-6.0.z.1 branch.

In master this is acceptable because nightly builds use the develop version. But, we are finding some differences in API on compose and nightly builds. Was talking with @Ichimonji10 yesterday about it and we did a session to come with some ideas. Probably today we will have a PR with the helper function suggestion.

**Comment by kbidarkar** [comment]
thanks for mentioning the branch here. Looks like I missed to mention the point here that this is for zstream and compose builds only.

**Comment by ripcurld00d** [comment]
By the way, unlike @kbidarkar I am running Satellite v6.0.4 and the version of foreman is `1.6-develop` too.
