### ISSUE TITLE
Improve handling of entities name that longer than 30 symbols in WebUI

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2913]
At that moment we have implementation of that functionality on the search level. For example, `environment` entity
```
    def search(self, name):
        """Searches existing env from UI"""
        Navigator(self.browser).go_to_environments()
        if len(name) <= 30:
            element = self.search_entity(name, locators['env.env_name'])
        else:
            element = self.search_entity(
                name, common_locators['select_filtered_entity'])
        return element
```

Such approach applied on next entities:

* [ ] `Config Groups`
* [ ] `Environment`
* [ ] `Hardware Model`
* [ ] `Medium`
* [ ] `Operating System`
* [ ] `Registry`

For other entities, we tried to use short strings (not more than 8 symbols)

We have to think on one solution that should be applied on higher level, so we can remove huge amount of redundant code and add proper support of long string for all entities in WebUI

**Comment by omaciel** [comment]
My proposal:

1. All cases where the locator for an entity changes depending on the length of the value passed to it should implement an xpath that handles both scenarios (eg. `//a[contains(., 'foo') or contains(@href, 'bar')]`
1. Every entity will use the existing `search_entity` method from `base.py`
1. If a generic xpath expression cannot be used, then the following actions should be performed:
  1. Consider submitting a pull request to the upstream project which would add  a unique ID
  1. Consider overriding the `search_entity` for the given entity:

```python
def search_entity(self, *args, **kwargs):
  # Check the length of the value you care about and
  # assign proper xpath expression
  # call super class with proper args + xpath
```

If anything else needs to happen that is currently not supported by `search_entity` then we should try to improve it so that it can handle.

**Comment by omaciel** [comment]
Another option would be to allow a locator to have multiple `xpath` expressions instead of only one. This would lead to code that goes from:

```python
    "menu.monitor": (
        By.XPATH,
        ("//div[contains(@style,'static') or contains(@style,'fixed')]"
         "//a[@id='monitor_menu']")),
```

to

```python
    "menu.monitor": [
        (By.XPATH,
        ("//div[contains(@style,'static')")),
        (By.XPATH,
        ("//div[contains(@style,'fixed')]//a[@id='monitor_menu']")),        
    ]
```

Then `search_entity` would attempt to locate the element iterating through the list of locators until a match was found **or** fail if none of the expressions allows it to find a match.

**Comment by sthirugn** [comment]
We should also support passing multiple strings to the search_entity. For example, we may have a locator like the following which has one than one string reference.  Currently, framework supports passing of one string only.
```py
    "arch.arch_name": (
        By.XPATH,
        "//a/span[contains(@data-original-title,'%s') or contains(., '%s')]"
    ),
```

**Comment by kbidarkar** [comment]
One can pass two strings to locator this way,
https://github.com/SatelliteQE/robottelo/blob/master/robottelo/ui/ldapauthsource.py#L57

```
element = self.wait_until_element((strategy1, value1 % (name, name)))
```

**Comment by oshtaier** [comment]
Task goals:
1) Verify whether all entities has mentioned problem with character length
2) Find out proper locators for such cases and use them. As alternative we can think about using next solution on base class level in case it is applicable for all scenarios and *only* if we decide that locators changes approach is nit optimal
```
    if len(name) <= 30:
        element = self.search_entity(name, locators['your_locator_name'])
    else:
        element = self.search_entity(
           name, common_locators['select_filtered_entity'])
```

**Comment by elyezer** [comment]
I see this being handled by a helper where it has all mappings (if they are different) for short version (with the `...`). It should be called by the search on base class in order to adjust the text and the locator being used to actual search.

**Comment by elyezer** [comment]
@oshtaier  discovered that Compute Resource which is a Foreman based entity don't change to ellipsis notation.

With that said, I think that a BZ can be opened and the workaround should be added to be executed while that issue is open. We need to guarantee same behavior, which will make the system more usable by our customers.

**Comment by oshtaier** [comment]
There are more of them:
```Location, Organization, ComputeResource, HostGroup, OpenScapContent, OpenScapPolicy```
So we decided to move on with Option 2 from:

Option 1:
Add one more class attribute. For example, `shorten_name`. Put it in `True` for all cases where name is transformed to 'name...' form.
Substitute:
```
if not self.is_katello and len(element_name) > 32:
    strategy, value = common_locators['select_filtered_entity']
```
on:
```
if self.shorten_name:
    strategy, value = common_locators['select_filtered_entity']
```

Option 2:
Have list of exceptions which contain class names that has unexpected behavior for use.
`EXCEPTIONS_LIST = ['Compute Resource', ...]`
```
if not self.is_katello and len(element_name) > 32 and type(self).__name__ not in EXCEPTIONS_LIST:
    strategy, value = common_locators['select_filtered_entity']
```

Option 3 (very time consuming):
Back to initial idea with complex locators for all entities
