### ISSUE TITLE
Combine all Downstream failures and Upstream failures

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#2915]
**Problem:**
We currently have 110 github issues just for automation failures.  This is hiding the real issues that need work/attention:
* 48 downstream failures
* 62 Upstream failures

**Proposal:**

1. Create two new github issues one each for `upstream` and `downstream` failures
1. Combine all the corresponding failures to these newly created issues.  
    For example:
    Upstream failures:
     - [ ] tests.foreman.smoke.test_smoke.SELinuxTestCase.test_installer_check_services
     - [ ] tests.foreman.smoke.test_api_smoke.TestAvailableURLs.test_get_links
     - [ ] tests.foreman.smoke.test_api_smoke
1. Once incorporating all the issues as explained above, close all the individual failure issues - We will be left with only 2 issues for automation failures.
1. When a failure is fixed, it can be marked with [x] or that corresponding item can be simply removed from the list.
1. This new method will not allow pasting of error messages but it can be obtained easily from jenkins.

**Result:**
Once this work is done, we will have 140 open issues vs. 248 as of today.

**Comment by omaciel** [comment]
ACK

**Comment by elyezer** [comment]
@sthirugn @tkolhar I'm adding this issue to the current milestone. Let get it done by the end of the week?

**Comment by tkolhar** [comment]
hi @elyezer  : here's what i did to cover this github issues:
Create 2 github issues one for upstream and one for downstream
- https://github.com/SatelliteQE/robottelo/issues/2931
- https://github.com/SatelliteQE/robottelo/issues/2929
These, issues contains list of all the failures related to each stream
After combining all the issues as explained above, I have closed all the individual failure issues - 
We are now left with only 2 issues for automation failures.
When a failure is fixed, it will be marked with [x] or that corresponding item will be simply removed from the list.

So, since I have covered this issue as expected we can close this issue
Thanks !!

**Comment by elyezer** [comment]
@tkolhar thanks for the update.

@sthirugn if you are OK then we can close this.

**Comment by sthirugn** [comment]
This is done.
