### ISSUE TITLE
Avoid running tests if required configuration is not set in robottelo.properties

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#3006]
Our smoke tests perform a series of actions with a VM, such as registering it and consuming content. However, if the setting `provisioning_server` is not set, these actions should be avoided/skipped without affecting the rest of the test.

**Comment by omaciel** [comment]
@sthirugn @JacobCallahan this should be applied to your refactoring of our smoke test suite.

**Comment by sthirugn** [comment]
Note that this is not specific to smoke tests, this should be applied to entire robottelo.

**Comment by svtkachenko** [comment]
@omaciel @sghai @sthirugn @oshtaier Bump for discussion.
Issue #3236 describes a problem when test fails because `None` would be substituted in case properties section/value is missing. However, while checking all cases of a settings sections usage I've found that sometimes it does not matter whether actual value would be used or `None`.
For example, https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_computeresource.py#L42-L43
CRUD tests pass just fine with `qemu+ssh://root@None/system` instead of real libvirt provider URL. Should I leave these tests as is or skip them with `skip_if_not_set`?

**Comment by omaciel** [comment]
@svtkachenko I think that if a setting is `None` then the test should be skipped.

**Comment by sghai** [comment]
Yeah.. what @omaciel said, lets wrap the tests or test class with `skip_if_not_set`
