### ISSUE TITLE
Fix / Update cli/test_organization.py

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/robottelo#3139]
The `cli/test_organization.py` module (formely `cli/test_org.py`) has several issues that need to be addressed:
* Some tests perform no assertions (booo!!!)
* Some tests are implemented but have the `stubbed` decorator. These need to be investigated
* Some low-hanging test cases that can be added.

**Comment by elyezer** [comment]
@abalakh can you please update the status?

**Comment by abalakh** [comment]
Status:
* ~~Some tests perform no assertions (booo!!!)~~ Done
* ~~Some low-hanging test cases that can be added.~~ Done
* Some tests are implemented but have the stubbed decorator. These need to be investigated - Will take a look

**Comment by elyezer** [comment]
:

**Comment by abalakh** [comment]
Hm... Right now only the tests which verify organization with smart proxy association are stubbed. I've tried to unstub them - they are 'freezing' on smart proxy creation, more specific - on executing [ssh -i {0} -t -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -L {1}:{2}:{3} {4}@{5}](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/cli/proxy.py#L54-L55) command. What is really weird that this command is neither passing nor failing by timeout and may keep alive forever (i got bored after 20+ minutes, don't think it will actually fail somewhen).
I've checked file history, last change was made in #3149. Tried to revert it - tests started to fail with errors, described in that PR, so it doesn't look like the PR broke functionality.
At first i thought that it is a new issue, but then i checked existing smart proxy tests and found one really interesting line: [Skipping tests until we can create ssh tunnels](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_capsule.py#L19). Now i'm not sure - should we be able to create smart proxies via CLI or we have an issue with ssh tunnels and those tests should remain stubbed?

**Comment by rplevka** [comment]
@abalakh 
the `ssh -i {0} -t -t -o StrictHostKeyChecking=no -L {1}:{2}:{3} {4}@{5} ` actually works and really does the port forwarding (no need for `-o UserKnownHostsFile=/dev/null`). However, paramiko won't return anything until the command finishes (you can also try to change the command to `vim` or anything like that) it won't quit.

I made it to work the following way though:
`u'ssh -i {0} -o StrictHostKeyChecking=no -fN -R {1}:localhost:{3} {4}@{5} > /dev/null 2>&1'`
- mind the `-fN` parameters.
this will fork the command to the other thread and leaves it in place after paramiko closes the session. The only disadvantage is, we loose the handle to the process, but the tunnel will stay in place (we need to take care of terminating the process manually after we're done.

the second obstacle was to make the forwarding accessible remotely. Local forwarding works, but only on accessing `https://localhost:<port>`. This way, the test fails on `SSLError` as the hostname does not match the one specified in a cert.
- introducing `-R` instead of `-L` makes the forward remote, however, the `sshd` daemon does not allow remote hosts to connect to the forwarded ports by default. To change this behaviour, we need to set `GatewayPorts` to `yes` in `/etc/ssh/sshd_config`.

**Comment by rplevka** [comment]
> - ~~Some tests are implemented but have the stubbed decorator. These need to be investigated - Will take a look~~
Tests unstubbed by implementing #3302

**Comment by abalakh** [comment]
> Tests unstubbed by implementing #3302

Thanks a lot :+1: 
Closing this issue
