### ISSUE TITLE
For rhel67, skip all container related tests using internal docker compute resource

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3207]

**Comment by elyezer** [comment]
@sthirugn internal docker compute resource is able to be tested it is just not officially recommended since the docker service is not a package from RH but from EPEL.

In order to implement this we will need information about the running OS as well as add a new decorator to support skipping based on the OS version.

**Comment by rochacbruno** [comment]
We already have decorator to check O.S version implemented by @renzon is this issue still valid? should we put on the queue?

**Comment by renzon** [comment]
Here it is an example of the decorator: https://github.com/renzon/robottelo/blob/9f8b561be4e6ded853312f0072b10936b203c6a0/tests/foreman/api/test_contentview.py#L1501-L1501. @sghai asked me for this decorator because OSTree feature is available only on RHEL 7+. So it can be used if needed.

**Comment by rplevka** [comment]
i'm closing this mostly because the last version of satellite which runs on rhel6 is going to be EOL pretty soon
