### ISSUE TITLE
Implement proper support for select lists for 6.2

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3329]
List of entities that are left to fix:
* [x] `activation_keys`
* [x] `content_views`
* [x] `discovery_rules`
* [x] `domains`
* [x] `gpgkeys`
* [x] `hosts`
* [x] `ldapauthsource`
* [x] `location`
* [x] `medium`
* [x] `operating_system`
* [x] `organization`
* [x] `partion_table`
* [x] `products`
* [x] `role`
* [x] `settings`
* [x] `syncplan`
* [x] `template`
* [x] `trend`
* [x] `usergroup`

**Comment by abalakh** [comment]
Marked the entities i've finished working on, others are in progress but have some issues which made me temporary leave them unfinished and switch to easier ones.
* organization - can't find parent organization selector, checked on sat6.2 and sat 6.1.8... either i'm missing something or it's just outdated and needs to be dropped
* partition_table - layout is typed in textarea, which is now replaced with Ace Editor. Probably need some time to investigate the ways of typing text into Ace Editor or update existing tests to use file upload instead of editor (same approach as for provisioning templates).
* usergroup - can't find external usergroups selector, checked on sat6.2 and sat 6.1.8... i bet i'm missing some configuration. Or maybe it's something pretty old and needs to be dropped

Will take a look at them tomorrow

**Comment by oshtaier** [comment]
Let's me check these three

**Comment by oshtaier** [comment]
Investigated `partition_table ` entity. Please proceed with file upload option as we can use only direct JavaScript injection to enter text for that specific editor and it doesn't seem as preferable option. There is a way to input text in editors like this using classical Selenium means in general, but not for our specific case as necessary textarea always stay hidden no matter you click on parent div or call mousedown/mouseup events

**Comment by oshtaier** [comment]
Regarding organization parent functionality:
https://github.com/Katello/katello/pull/4362
https://bugzilla.redhat.com/show_bug.cgi?id=1109737

Please, drop all code that referring to that functionality. Both locators, factory code and test case.
We can add it in future if ever need it

**Comment by oshtaier** [comment]
Regarding usergroup. Yes, you are missing something:) :
![image](https://cloud.githubusercontent.com/assets/10895065/13697594/093f724a-e777-11e5-9bf4-64af2ddd64f4.png)

**Comment by abalakh** [comment]
@oshtaier thanks for help!
Regarding usergroup - this tab is missing for me. I suspect i need to configure ldap first, lemme try...
