### ISSUE TITLE
Add a ClientFactory to flexibilize client provisioning in tests

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/robottelo#3607]
Some tests like this: https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_contenthost.py#L81

uses:

``` python
self.client = VirtualMachine(distro='rhel7')
```

It would be great if we can replace that with

``` python
self.client = ClientFactory(distro='rhel7')
```

And then, **ClientFactory** would be an AbstractFactory reading properties file to decide if:
- provide a new VirtualMachine
- reuse existing VirtualMachine
- use a docker container
- point to external client
- point to some PaaS service

In robottelo.properties currently we have:

``` ini
[clients]
provisioning_server=FQN.domain.com
image_dir=/opt/robottelo/images

```

we can add

``` ini
[clients]
client_type=docker|libvirt|vbox|vagrant|openshift|external|existing|aws (etc...)
docker_server=local
docker_registry=
docker_image=
vagrantfile=/etc/tools/satellite_vagrant
openshift_domain=foo.com
openshift_credentials=x,y
provisioning_server=FQDN.domain.com
image_dir=/opt/robottelo/images
```

The default should be **libvirt** with provisioning_server, but the idea is to add flexibility and also allow us to run some tests locally using docker or local virtual manager

**Comment by sghai** [comment]
This would help going forward to run host specific tests on docker containers and that saves lot of time and resources. Great move. thanks

**Comment by elyezer** [comment]
The VirtualMachine class was developed in order to be the proposed ClientFactory. Currently it just supports libvirt, but we can improve it and add support to more client provisioning systems.

With that said VirtualMachine should be a "generic" class that will choose one of the `LibvirtVirtualMachine` or `DockerVirtualMachine` for example.

What I am saying is that this proposal is a really good idea but instead of adding a new name to use the VirtualMachine.

**Comment by rochacbruno** [comment]
@elyezer dont you think ClientFactory is a better name?  We have VM, containers, existing systems etc... not all are VMs.

**Comment by elyezer** [comment]
@rochacbruno I was talking about the client instance, since you raised about the naming which I really think is better to rename but I would suggest to call ClientMachine or RemoteClient or something like that for the instance you will be interacting with. A factory can exist just for the sake of creating a client machine or a remote client.

I don't have strong preference here, just dropping some suggestions. To reinforce, renaming makes sense to me.

**Comment by ldjebran** [comment]
@rochacbruno  robottelo VirtualMachine needs refactoring especially after adding a custom hostname,
by separating the provisioning server functionality from the virtual machine one.
Creating a base provisioning server and LibVirt provisioning server that inherit from base
The provisioning server is passed to VirtualMachine as instance class and not as hostname, (By default LibVirt provisioning server is used).
that way we can use any virtual machine with static hostname or virtual machine provisioned by an other provisioning server.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
