### ISSUE TITLE
Fix tests.foreman.api.test_subscription.SubscriptionsTestCase.test_positive_delete

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3618]
```
Error Message

TaskTimedOutError: Timed out polling task 72bda5d1-1552-40e2-9a59-fe7d6734d82b. Task information: {u'username': u'admin', u'ended_at': None, u'output': {}, u'cli_example': None, u'label': u'Actions::Katello::Provider::ManifestDelete', u'state': u'running', u'result': u'pending', u'input': {u'remote_cp_user': u'admin', u'organization': {u'label': u'yjSfAFm', u'id': 900, u'name': u'yjSfAFm'}, u'remote_user': u'admin', u'provider': {u'id': 1408, u'name': u'Red Hat'}}, u'progress': 0.0, u'started_at': u'2016-07-15 21:49:06 UTC', u'humanized': {u'action': u'Delete Manifest', u'input': [[u'organization', {u'text': u"organization 'yjSfAFm'", u'link': u'/organizations/900/edit'}]], u'errors': [], u'output': u''}, u'id': u'72bda5d1-1552-40e2-9a59-fe7d6734d82b', u'pending': True}
```

**Comment by renzon** [comment]
Running the test I got [msgs](https://gist.github.com/renzon/7af05f7f7440ffb5850758108454b371) for more than 10 minutes. I am going to investigate

**Comment by renzon** [comment]
The code timeout here: https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entity_mixins.py#L89. task_info is 'running' all the time

**Comment by renzon** [comment]
What is affecting both this issue and #3617 is [upload_manifest](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/api/utils.py#L63). Once you start it the job take a long time to be done. The is one Taks that didn't finished after 1 hour. I've written a code to check the time a task is consuming until completion, if it get completed at all: http://pastebin.test.redhat.com/393392. Let's see the result after some time running.

**Comment by renzon** [comment]
The result completed: http://pastebin.test.redhat.com/393406. Tasks took 58 minutes to complete.

**Comment by sghai** [comment]
@renzon: thanks.. nice analysis. Ideally, import manifest should not take that much time.

**Comment by omaciel** [comment]
@sghai @renzon I noticed that when we try to import a manifest for a test, usually a `sequentially` executed test such as `cli/test_subscription`, `cli/test_reposet` or `cli/test_repositories`, the system is already loaded with a ton of data from the tests run in parallel. Importing or deleting a manifest then could take ~12 minutes each! However, if the system is not as loaded (see the results from `Tier 4` for an example), the manifest takes less than 30 seconds to import.

**Comment by sghai** [comment]
@omaciel : yeah, need to investigate if issue is with manifest or something related to infra. Another reason could be some other tests running in parallel to manifest import.

**Comment by renzon** [comment]
@omaciel. @sghai  The ton of data was in my mind. But in this particular case I run only this sindle test. Although the system is full of data from previous test cases which I run due another issues. Should I install a fresh Satellite to validate this?

**Comment by renzon** [comment]
@sghai @omaciel or would have an easier way to test this without fresh installation? If this is the case, test will be ok only when we solve tearDown issues, right?

**Comment by renzon** [comment]
Yesterday I changed the test case. After take that long to import a manifest, I changed the test to used this already imported:

'''python
org = entities.Organization().search(
            query={u'search': u'name="JxUAldoW"'}
        )[0]
        sub = entities.Subscription(organization=org)
        # with manifests.clone() as manifest:
        #     upload_manifest(org.id, manifest.content)
        self.assertGreater(len(sub.search()), 0)
        sub.delete_manifest(data={'organization_id': org.id})
        self.assertEqual(len(sub.search()), 0)
'''
### Result
After that I run the pooling code again because it also was taking to much time (1:10, you can see the result above). This way I could "run" the test itself, which would pass without timeout setting, but would take 2 hours to finish. So basically  any operation on manifest is taking too much time.

Result from deleting
18:06:47
18:06:49

{'input': {'remote_cp_user': 'admin', 'organization': {'label': 'JxUAldoW', 'id': 1282, 'name': 'JxUAldoW'}, 'remote_user': 'admin', 'provider': {'id': 1836, 'name': 'Red Hat'}}, 'label': 'Actions::Katello::Provider::ManifestDelete', 'started_at': '2016-07-18T21:06:17.000Z', 'username': 'admin', 'progress': 0.0, 'state': 'running', 'output': {}, 'result': 'pending', 'pending': True, 'ended_at': None, 'id': 'ab5a2a35-8e00-41a3-a2bb-7dec1d585552', 'cli_example': None, 'humanized': {'action': 'Delete Manifest', 'input': [['organization', {'link': '/organizations/1282/edit', 'text': "organization 'JxUAldoW'"}]], 'output': '', 'errors': []}}
18:13:03
18:19:20
18:25:37
18:31:54
18:38:12
18:44:29
18:50:48
18:57:06
19:03:23
19:09:41
19:16:02
19:21:22

19:21:32
Fisished

**Comment by renzon** [comment]
@sghai @omaciel With the hint of @rochacbruno reseted the system: satellite-installer --reset.

Test run in only 30 seconds. The same for #3617.

What should we do with this issues related to manifest manipulation?

**Comment by renzon** [comment]
Closed in favor of #3628

**Comment by rochacbruno** [comment]
@omaciel it is possible to enable the org cleanup (already implemented) only for `api/test_subscription`, but we may end with the same DEADLOCK error in tasks. we should try to see if this is still happening.

**Comment by sghai** [comment]
Org deletion always be a risky task specially when multiple entities are associated with it, like CV/hosts etc. Instead, we should see if can minimize org creation at test level. We should create one org per test_module, if it satisfies all test requirements.
