### ISSUE TITLE
The jobs should use it's own respective sat-tools repos

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/robottelo#3698]
Our Robottelo automation should pick up dynamically depending upon various pipeline/releases the SatTools versions.
1) For Sat6.1.z
We need to enable and sync SatTools RH Repo 6.1 version 
2) For Sat6.2.z
We need to enable and sync SatTools 6.2 custom repos
For custom repos, we can make use of this config param, https://github.com/SatelliteQE/robottelo-ci/blob/master/scripts/satellite6-automation.sh#L84 from `robottelo.properties` file.
This value is populated from `Satellite 6 Repos URLs Environment Variables` configfile.
3) For Sat6.2 GA  
We need to enable and sync SatTools RH Repo 6.2 version 
4) For Sat6.3 
We need to enable and sync SatTools 6.3 custom repos
For custom repos, we can make use of this config param, https://github.com/SatelliteQE/robottelo-ci/blob/master/scripts/satellite6-automation.sh#L84 from `robottelo.properties` file.
This value is populated from `Satellite 6 Repos URLs Environment Variables` configfile.

**Comment by rochacbruno** [comment]
As per @oshtaier comment on IRC:

> need to have for example 'Red Hat Satellite Tools 6.1 for RHEL 7 Server RPMs x86_64' for 6.1 Satellite and 'Red Hat Satellite Tools 6.2 for RHEL 7 Server RPMs x86_64` for 6.2 so depends on Satellite version have different specific pre-defined constants.

I did this POC:

```python
REPOSET = VersionedDict({
    "6.1.x": {
        'rhct6': 'Red Hat CloudForms Tools for RHEL 6 (RPMs)',
        'rhel6': 'Red Hat Enterprise Linux 6 Server (RPMs)',
        'rhva6': (
            'Red Hat Enterprise Virtualization Agents for RHEL 6 Server (RPMs)'
        ),
        'rhst7': 'Red Hat Satellite Tools 6.2 (for RHEL 7 Server) (RPMs)',
        'rhst6': 'Red Hat Satellite Tools 6.2 (for RHEL 6 Server) (RPMs)',
    },
    "6.2.x": {
        ...
    },
    "general: {
       ...
   }
})
 
# access normally
 
REPOSET['rhst7']
 
# the above will vary accordingly to sat version
# values in "general" will always take precedence
```

Question: @oshtaier @kbidarkar 

from where "satellite version" can be taken? as test runs in jenkins we need to make ssh call to get satellite version? ( @renzon that decorator you created can do that? ) or we already have the version as environment variable or jenkins variable?

**Comment by renzon** [comment]
@rochacbruno In fact I got only OS version. It was through SSH: https://github.com/SatelliteQE/robottelo/blob/master/robottelo/decorators/host.py#L19

**Comment by renzon** [comment]
It could be used same approach:

```console
[root@mgmt5 ~]# rpm -q satellite
satellite-6.2.0-21.1.el7sat.noarch
```

**Comment by sghai** [comment]
```console
[root@mgmt5 ~]# rpm -q satellite

This ^ rpm is only available with 6.2 (not with 6.1)

`SATELLITE_VERSION` env variable being set but that we can use only with automation-tools not with robottelo.

**Comment by rochacbruno** [comment]
@sghai so we need to handle a different command in 6.1, do you know which command is this?

**Comment by sghai** [comment]
I don't think if we have any cmd to check version for 6.1, but here are the files that we can use to get the version.

`/usr/share/foreman/lib/satellite/version.rb` <- 6.1

`/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_theme_satellite-0.1.25/lib/foreman_theme_satellite/version.rb` <- 6.2

**Comment by renzon** [comment]
@oshtaier the feature iself is done: https://github.com/renzon/robottelo/commit/0eb6f4d0b0a41e284cd55924215945dcc1986a3c

But I have tried some test that uses REPOS and they fail because some try access repos which are on 6.1 but not in 6.2, like [this one](https://github.com/renzon/robottelo/commit/6095e9ca0e22b835dde378f5cbc7257a337f1bc9#diff-a406ed901ba0cbdfe6ad42357d74ca7eR207). Do you have sugestions to add for these values? I would put stub value, only changing version number, but dont know if they must match some real repo or not.

**Comment by oshtaier** [comment]
https://github.com/renzon/robottelo/commit/0eb6f4d0b0a41e284cd55924215945dcc1986a3c only contains interaction regarding OS version
https://github.com/renzon/robottelo/commit/6095e9ca0e22b835dde378f5cbc7257a337f1bc9#diff-a406ed901ba0cbdfe6ad42357d74ca7eR207
contains more things and I see some actions for Sat version. Let's me check it

**Comment by oshtaier** [comment]
Yes, it should work, changing `6.1`->`6.2` works for Sat Tools repo

**Comment by oshtaier** [comment]
Here I want ask whether another approach (which can be implemented in future, not now) gonna work for us or it is bad from the start. Does it make sense to have isolated constant file depending on the Sat version which will be loaded for that specific version? Or if master is supported only for one release, so we can use only one set of data and do not support 6.1, 6.2, 6.3 and etc? Otherwise, as I said, we can have const_6.1, const_6.2 and etc. The idea that if we tomorrow will need not only REPOS const, but some other be changed in the same manner, we can waste a lot of time for unnecessary PRs

**Comment by rochacbruno** [comment]
@oshtaier having two different modules will force us to use a conditional import `if "6.1" import a else import b` works, but using a `VersionedDict` in constants will make it seamless and also is lazy. If added at the import time one call will be made in the first time robottelo is imported, but in a `VersionedDict` the `if` will be lazy.

**Comment by kbidarkar** [comment]
>> `SATELLITE_VERSION` env variable being set but that we can use only with automation-tools not with robottelo.

I think the easiest would be to make the above env_variable pass the satellite_version info to `robottelo.properties` file.

Let me know if you folks think this is needed, I can raise a robottelo-ci and robotelo PR and make sure we include that. Then tests can check this variable and choose accordingly depending on version.

The downside which I would see here is we would need to flip the value manually , when testing locally in the `robottelo.properties` file.

**Comment by renzon** [comment]
@oshtaier the feature iself is done: https://github.com/renzon/robottelo/commit/0eb6f4d0b0a41e284cd55924215945dcc1986a3c

But I have tried some test that uses REPOS and they fail because some try access repos which are on 6.1 but not in 6.2, like [this one](https://github.com/renzon/robottelo/commit/6095e9ca0e22b835dde378f5cbc7257a337f1bc9#diff-a406ed901ba0cbdfe6ad42357d74ca7eR207). Do you have sugestions to add for these values? I would put stub value, only changing version number, but dont know if they must match some real repo or not.

**Comment by renzon** [comment]
@kbidarkar I have implemented following @sghai instructions. But if you have an easier way to get version through ssh, would be great.

**Comment by renzon** [comment]
@oshtaier @rochacbruno  I like the idea of importing different version because it make it simpler then making a new class overriding __getitem__ and doing some insede it. If we think that most of times tests do o role bunch of host access would not be a problem making this access on import time. The only drawback I see is that if you import constants but does not use any Sat version dependent constant you would waste time checking for this on repo. Or worse, your test will fail if some problem happens on version extraction. Maybe if we split them on "constant" and "sat_depedent_constantes" we could avoid it. So it would be simpler and not wasting resources. What you guys think?

Another thing: with currently approach we would need to create new REPOS and REPOSET for every new version. That is good? Or should we use some version data, let's say the last one, if the version data is not available?

**Comment by oshtaier** [comment]
Huh, now you explained the main drawback. If something go wrong with Sat version identification in dynamic import approach - we will have 1500 failed tests as no constant will be imported at all, in your current approach only 10-20 cases will fail

**Comment by renzon** [comment]
@oshtaier yes. In fact that was implicit on @rochacbruno "lazy" comment. But he explained me and I thought would clear things, once I hate introducing complexity on code for no reason. But he convinced me when with that reason ;)

**Comment by rochacbruno** [comment]
@renzon @oshtaier I personally think that conditional imports (with ifs) and performing I.O (ssh call) at the import time is more complex than using python data model (a.k.a `__dunder_methods__`) to implement magics :P 

Our friend's book has a nice chapter explaining why it is not complex but a tool working for simplicity (of use)!  https://www.safaribooksonline.com/library/view/fluent-python/9781491946237/ch01.html

**Comment by rplevka** [comment]
@kbidarkar - why don't we specify the version statically somewhere? e.g. `robotello.properties`.
We can change the value per branch. So in `master` branch (right now) it will be `6.2`. We can change it to 6.1 in 6.1 branch.

**Comment by kbidarkar** [comment]
@rplevka, @rochacbruno , @renzon, @sghai  I was suggesting we pull in the information of the version from an ENV_VAR and pass it in to the `robottelo.properties` file.

1) Automation would use the SATELLITE_VERSION we set manually from the jenkins UI and pass it to the `robottelo.properties` file.
2) Manually running the automation would then require to set the satellite_version in `robottelo.properties` file manually. 

This would avoid trying to SSH. But as mentioned earlier we would need to set it manually for the option 2) .

This is what I had meant in the above comment, https://github.com/SatelliteQE/robottelo/issues/3698#issuecomment-239391772.

Now the test-cases could  sync the desired sat-tools repo as per the value set in `robottelo.properties` file.

**Comment by renzon** [comment]
@rplevka @kbidarkar Once only one ssh call for the entire test, It doesn't add much more time on testing while avoiding more config and manual hassle when testing locally.

If we go for branch approach maybe it would be unnecessary knowing exactly sat version because different repos would be on this file: https://github.com/SatelliteQE/robottelo/blob/master/robottelo/constants.py#L199.

So this file would be cleaner. The downside is the porting back feature from master to branch.

So I see 2 different solution:

1. Keep specific config on branch. Pro: Framework code get cleaner. Con: Porting back can be an issue; have to maintain different pipelines for different versions
2. Keep framework agnostic. Pro: can use master to test whatever version, no porting back hassle; Its is already working with this, no need to different pipelines. Cons: Framework get more complex, having to introspection sat version

It seem people preffered option 2 on scrum mtg. 

 Commenting more people which contributed on mtg discussion:
@omaciel @sghai @rochacbruno @lpramuk

**Comment by kbidarkar** [comment]
With this approach https://github.com/SatelliteQE/robottelo/issues/3698#issuecomment-241047940, no branching needed, no SSH needed and no need to portback stuff or maintain stuff explicitly as per branches, If I am not missing anything. :)

**Comment by kbidarkar** [comment]
I am reopening this issue, we need support for the scenario 2) and 4).  

The idea is use Red Hat repos from manifest for CDN job. 1)satellite 6.1 3)satellite 6.2 
and for all other purposes use sat-tools custom repo for all other jobs. ( zstream, downstream, upstream. )

We can pick the below value for custom sat-tools repos.
https://github.com/SatelliteQE/robottelo-ci/blob/master/scripts/satellite6-automation.sh#L84

**Comment by kbidarkar** [comment]
Currently considering Sat6.1.z ~= Sat6.1 GA , as we may have bare minimum changes and hence can be used via enabling RedHat Repos. If anyone thinks otherwise please consider sat-tools custom repos for this as well.
