### ISSUE TITLE
Improve bz_bug_is_open() logic

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#3896]
_obsoleted comments - pls skip to_ https://github.com/SatelliteQE/robottelo/issues/3896#issuecomment-252206282

bz_bug_is_open() logic is wrong:

```
if bug is None or bug.status not in BZ_OPEN_STATUSES:
    # if not upstream mode, verify whiteboard field for the presence of
    # 'verified in upstream' text
    if (not settings.upstream and bug.whiteboard and
            'verified in upstream' in bug.whiteboard.lower()):
        return True
```

if bug is _ONQA, VERIFIED, CLOSED_ and we are testing _downstream_ and whiteboard contains _'Verified in Upstream'_ then bug is wrongly skipped (True = open -> skip) !!!

Only thing which prevented to exhibit this wrong logic is `robottelo.properties` file used in Downstream automation with wrongly set `upstream=True` 
(actually we have only 1 copy of robottelo.properties - not distinguishing between downstream and upstream) 

I'm going to rewrite it as I did for automation-tools in https://github.com/SatelliteQE/automation-tools/pull/399

**Comment by rochacbruno** [comment]
Because of that, some weeks ago, for standalone automation I included a text field allowing us to specify properties file for each build.

**Comment by lpramuk** [comment]
I will change Robottelo Config in Jenkins to have ```upstream=false``` once fixing PR is merged.

Later on we need to add sed command to ```s/upstream=.*/upstream=true/``` for *nightly-automation* job.

**Comment by rochacbruno** [comment]
@lpramuk @omaciel  also this should be cpicked to Z branches?

**Comment by sthirugn** [comment]
@lpramuk: This is not an issue and working as expected.

What happens when we verify bugs in upstream?
- We move the bug to 'Verified' or 'Closed' status
- Mark whiteboard as 'verified in upstream'
Say this happened for a specific bug - it means the fix is available in upstream,  but not yet ported to downstream.  - Again it means, this test can be run in upstream `but` it should be skipped in downstream, although the bug status is in closed status.
Note: This process was implemented as part of https://github.com/SatelliteQE/robottelo/commit/6d8fb67a6eb4436505c2fad597301ef6eb29c77f - which explains this logic.

How do we handle robottelo-ci? why does the jenkins robottelo file has upstream=True?:
Yes the default is set to upstream=True in jenkins and this will be accordingly set to False in robottelo-ci depending on the distribution parameter.
See https://github.com/SatelliteQE/robottelo-ci/blob/2e2b4991551bca2be39d6feb3896adeb40185c03/scripts/satellite6-automation.sh#L59-L62

As per the proposed process, once the upstream fix lands in downstream, we should go back and remove 'Verified in upstream' text in the bugzilla - I don't think this is happening now and should be fixed.  I created an issue to track this - https://github.com/SatelliteQE/robottelo/issues/3898.

**Comment by lpramuk** [comment]
I agree with you on the process. but still logic is not that:
Lets read if:
1. bug.status not in BZ_OPEN_STATUSES  ```[=ONQA, VERIFIED, CLOSED]```
    and 
    2. not settings.upstream ```[=DOWNSTREAM] 
         and
        3. whiteboard has 'verified in upstream' [=VIU]
=> return true (is open) => SKIP

```
[ONQA, VERIFIED, CLOSED]:
[DOWNSTREAM] [VIU] [SKIP]
               1                 1        1
               1                 0        0
               0                 1        0
               0                 0        0
```
1                                                    1

**Comment by sthirugn** [comment]
`=> return true (is open) => SKIP `

In your scenario, Yes this is what is expected  :)

**Comment by lpramuk** [comment]
I was fixing this for imaginary process in my head, Suresh explained me that it works differrently (not really awesome),  and thus no fix needed....

But I was able to come up with a decent imporvent of this process so we dont have to get back to closed bugs and remove 'Verified in Upstream' out of whiteboard - ugly to have these bugs started to be tested in downstream.

I propose to take advantage of more granular states in BZ - that is to distinguish between 'VERIFIED' and 'CLOSED' - once the bug is set to 'CLOSED' state start testing it in Downstream no matter what whiteboard is. 

Thus no need for removing 'Verified in Upstream' out of whiteboards :-)

**Comment by lpramuk** [comment]
I will use this issue to improve the logic that way (instead of fixing)

**Comment by lpramuk** [comment]
I'm done by just adding ```and bug.status != 'CLOSED'``` into relevant if clause

**Comment by lpramuk** [comment]
PR https://github.com/SatelliteQE/robottelo/pull/3897

**Comment by lpramuk** [comment]
Closing as changes have make it into all 3 branches.
