### ISSUE TITLE
Fix smart variables test failures

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/robottelo#3938]
IMO current picture of failures for smart variables is a bit too much and worth analysis:

| Module | Tier 1 | Tier 2 | Total |
| --- | --- | --- | --- |
| API | 30 | 3 | 33 |
| CLI | 4 | 5 | 9 |
| UI | 11 | 18 | 29 |
|  |  |  | _71_ |

**Comment by abalakh** [comment]
@oshtaier @svtkachenko guys could you please take a look at these failures as you've been working with smart variables the most? If not i can pick them up.

**Comment by svtkachenko** [comment]
For the moment I can see 2 reasons of failures:
1. Puppet module was removed in one testcase while another still was running. I'm going to create several custom puppet modules per testacase. Should be easy.
2. 'Production' puppet environment was not found. Looks like it is installation problem that should be solved because as for me creating of separate puppet environment looks like a real pain -- requires a lot of config files editing on server side. But maybe I'm wrong.
