### ISSUE TITLE
add tests for hammer realm subcommand

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#4081]
6.3 introduced the `hammer realm` subcommand:
```
hammer realm -h
Usage:
    hammer realm [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
 SUBCOMMAND                    subcommand
 [ARG] ...                     subcommand arguments

Subcommands:
 create                        Create a realm
 delete                        Delete a realm
 info                          Show a realm
 list                          List of realms
 update                        Update a realm

Options:
 -h, --help                    print help

```
This issue is to track efforts around testing the realm manipulation through CLI.

**Comment by chbrown13** [comment]
Realm feature needs to be set up and added for capsules-

 Command "realm create" finished with return_code 65
E           stderr contains following message:
E           [ERROR 2017-07-12 09:31:36 API] 422 Unprocessable Entity
E           [ERROR 2017-07-12 09:31:36 Exception] Realm Capsule does not have the Realm feature
E           Could not create the realm:
E             Realm Capsule does not have the Realm feature

**Comment by san7ket** [comment]
You need to have Realm feature enable on the capsule, follow 6.2 docs for

**Comment by kbidarkar** [comment]
some information about realm feature. This could be very tricky implementing and I feel should probably have it's own jenkins job. Currently I am not sure how this can be automated along with DNS Capsule Feature enabled for our automation.
1) This feature is Infrastructure locked, would work only with that host, who's hostname and IP is already part of an IDM Server and is pointed to the IDM Server in the `/etc/resolv.conf` file. For this reason, Beaker setups, which have sat6 installed on them cannot be used, because of the above mentioned reasons.
2) REALM Feature is also mutually exclusive to DNS Capsule Feature and DNS Capsule Feature is by default enabled for all of our Satellite6 setups.

**Comment by chbrown13** [comment]
Ok, good to know. Will hold off on adding this for now.

**Comment by chbrown13** [comment]
Thanks for your help @kbidarkar, was successfully able to create realms and add tests

**Comment by chbrown13** [comment]
Automated tests must be run on SatQE host (qe-testing-rhel7.satqe.lab.eng.rdu2.redhat.com)
