### ISSUE TITLE
Implement new tests around CV version removal

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#4101]
One test is around capsule. Let's see if we can add support around that.

**Comment by ldjebran** [comment]
@sghai @kbidarkar , After working on capsule issue plaese see code diff code here: https://github.com/SatelliteQE/robottelo/compare/6.2.z...ldjebran:%234101_CLI_CAPSULE?expand=1
the log of the test: http://pastebin.test.redhat.com/441831
satellite installer error log fragment(full log too big, if needed can send it by mail):   http://pastebin.test.redhat.com/441830
for me it seems that satellite cannot resolve the hostname of the vm

**Comment by kbidarkar** [comment]
So, we need Infrastructure in place, so that we can automate Capsule related stuff.

Current Issue:
1) The VM's provisioned on ginger using the robottelo/vm.py, will have only one sided DNS resolution.
2) VM's provisioned on ginger can resolve the SAT6 HOSTNAME
3) SAT6 server won't be able to resolve the VM's HOSTNAME and hence these ginger VM's cannot be used as CAPSULE machines.

Plan to create Capsule VM's:
1) For Capsule's we can make use of the DDNS feature while creating the VM's on ginger.
a) Create the entries for Sat61, Sat62, Sat63 ( RHEL6 + RHEL7 ) in https://hdn.corp.redhat.com/redhat-ddns/admin/view.php
b) The hostnames would be, `existing sat6 hostname`+`-capsule`.usersys.redhat.com
Example: qe-sat62-rhel7-capsule.usersys.redhat.com
This way dynamically we can make use of,
 capsule_hostname="{1}-capsule.{2}".format(settings.server.hostname, domain_name)
2) We will need to update/tweak the robottelo/vm.py to be able to specify the below at the time of provisioning.
a) hostname`of vm and
b)  `domain=usersys.redhat.com`.
3) This way for capsule both the Capsules and Sat6 would be able to communicate with each other.

**Comment by rochacbruno** [comment]
@ldjebran @sghai tests for API e CLI were merged. There is still UI tests to be written? or this issue can be closed?

@kbidarkar The points you wrote above may go to a new issue (or different new issues) ? So we don't lose it when this was closed.

**Comment by ldjebran** [comment]
@rochacbruno This issue cannot be closed for the moments,
UI PR in review #4184 
remaining : 
- 6 tests (CLI, UI, API) remove env with subscribed hosts attached.
- 3 tests (CLI, UI, API) remove env with capsule.

**Comment by ldjebran** [comment]
@rochacbruno think this issue should rest opened till implementation of all the tests.
30 tests in total 
tests implemented: 21
tests remaining: 9

**Comment by ldjebran** [comment]
* The 6 hosts tests blocked: https://bugzilla.redhat.com/show_bug.cgi?id=1406315
* The 3 capsule tests waiting infra implementation

**Comment by ldjebran** [comment]
@kbidarkar @sghai, after  we have updated VirtualMachine to support hostname, updateed my code
https://github.com/SatelliteQE/robottelo/compare/6.2.z...ldjebran:6.2.z-implement-cli-capsule?diff=split&expand=1&name=6.2.z-implement-cli-capsule

but still have some errors,  but this time not related to dns as now the host is resolved properly, the automation script  wait until the dns records are updated and point to the right IP address, by performing a ping from sat host.
the ddns setup looks like http://pastebin.test.redhat.com/457485 and is passing normally

the last errors looks like this: 
```console
 Proxy robottelo-sat62-rhel7-capsule.usersys.redhat.com cannot be registered (422 Unprocessable Entity): Unable to communicate with the Capsule: ERF12-2530 [ProxyAPI::ProxyException]: Unable to detect features ([Errno::EHOSTUNREACH]: No route to host - connect(2) for "robottelo-sat62-rhel7-capsule.usersys.redhat.com" po...) for Capsule https://robottelo-sat62-rhel7-capsule.usersys.redhat.com:9090/features Please check the Capsule is configured and running on the host.
[ERROR 2017-02-21 07:26:08 main]  /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[robottelo-sat62-rhel7-capsule.usersys.redhat.com]/ensure: change from absent to present failed: Proxy robottelo-sat62-rhel7-capsule.usersys.redhat.com cannot be registered (422 Unprocessable Entity): Unable to communicate with the Capsule: ERF12-2530 [ProxyAPI::ProxyException]: Unable to detect features ([Errno::EHOSTUNREACH]: No route to host - connect(2) for "robottelo-sat62-rhel7-capsule.usersys.redhat.com" po...) for Capsule https://robottelo-sat62-rhel7-capsule.usersys.redhat.com:9090/features Please check the Capsule is configured and running on the host.
```
Created a new DummyVirtualMachine see may code to test the same code with a beaker VM:
and the result was successful: http://pastebin.test.redhat.com/457426  (note the lines in yellow) 
Perhaps there is some ports blocked some where.
any idea?

**Comment by rplevka** [comment]
@ldjebran ,
> the last errors looks like this

```
# firewall-cmd --zone=public --add-service=RH-Satellite-6
```

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
