### ISSUE TITLE
UI - test_adusergroup.ActiveDirectoryUserGroupTestCase.test_positive_add_admin_role failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4163]
the tests has been failing for a long time.
It looks like there's some issue with obtaining an element in tearDown method:

```
    def tearDown(self):
        with Session(self.browser) as session:
>           set_context(session, org=ANY_CONTEXT['org'])

tests/foreman/ui/test_adusergroup.py:73: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
robottelo/ui/factory.py:107: in set_context
    select_context = check_context(session)
robottelo/ui/factory.py:81: in check_context
    ActionChains(session.browser).move_to_element(current_text).perform()
../../shiningpanda/jobs/9c131512/virtualenvs/d41d8cd9/lib/python2.7/site-packages/selenium/webdriver/common/action_chains.py:72: in perform
    action()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    self._actions.append(lambda:
>       self._driver.execute(Command.MOVE_TO, {'element': to_element.id}))
E   AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by oshtaier** [comment]
<oshtaier> kbidarka: it seems that email is become mandatory parameter for users like this. I looked in a way to fix it on robottelo side, but it seems as not good option for at least 6.3. Could we make change for it on infrstructure side?
<oshtaier> kbidarka: so when we use it in Satellite, it has assigned email by default
<kbidarka> oshtaier, I need to look into it, will see, I think I need to provide an email at the AD side itself , will investigate and let you know on IRC or drop a mail to you 
<oshtaier> kbidarka: thanks, because it is blocking all cases for both 6.2 and 6.3 for that functionality and treated as high priority, because numbers of failures it produces
<kbidarka> oshtaier, agreed

**Comment by oshtaier** [comment]
Fixed on infrastructure side:
```
nosetests tests/foreman/ui/test_adusergroup.py -m positive_add_admin_role
.
----------------------------------------------------------------------
Ran 1 test in 74.375s

OK
```
