### ISSUE TITLE
UI - entity details rendering failures

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4579]
This is not happening all the time,
I've checked the passed tests and they also use unicode names.
![img](http://storage3.static.itmages.com/i/17/0419/h_1492602673_2959127_3899a6e083.png)

occurred for the following strings:
兹ဃ묠彯蔋딕𠮅𤧣𦦋𠨲
𨷰𡰀촉𢽕𪥶𤸽𤻀剂

**Comment by abalakh** [comment]
This one is pretty old random failure, i've tried to analyze it long time ago. My findings were - issue happened to multiple entities, not just sync plans. It's pretty random - some utf8 names are working ok. It's not reproducible locally with exactly the same name. And my idea was to find such tests and try to not use unicode in names for them - as we decided not to use unicode in names anyway to increase readability and make debugging easier. Had no time to try it out though :(

**Comment by san7ket** [comment]
@ntkathole I have seen these failures mostly clubbed around synplans and gpgkeys test  cases, could you take a look and see if we can fix something in the tests itself. 
In upgrade, we have atleast 3 failures per build , regarding this issue and it's not feasible to keep the end-to-end tests having failed due to this issue.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
