### ISSUE TITLE
Having a single requirements file?

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/robottelo#4594]
I was setting up a project in Pycharm in robortello and ran into an issue when trying to run the stuff. Pycharm can use a requirements.txt file to automatically install requirements. It defaults to requirements.txt but you can change it.

However, I ran into to issues when trying to use sauce labs libraries: 

The saucelabs requirement was in ``requirements-optional.txt``, which pycharm didn't know about, and i couldn't tell to use both.

So questions are this:

1. Why do we have 2 requirements files again? 

2. If we do really want to seperate requirements in to a set of core requirements and "debug/devel" requirements, perhaps we can use the documented the requirements ``-r more_requirements`` option [described here](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) to create a file that includes both the "base" and "optional" ones. \
\
This would make it so when you did an install all you would have to do to run ``pip install -r requirements-all.txt`` to get everything. 

3. Not matter what we do. Any particular reason saucelabsclient is not in ``requirements.txt`` ? Are we just waiting till we test it a little more?

@elyezer @omaciel @rochacbruno @sghai + anyone else, thoughts on this?

**Comment by elyezer** [comment]
Sauce Labs requirements are not on the main file because it is not required to run you can run robottelo without it in place. By not having it on the main file also saves time when installing robottelo and the requirements are more aligned which is real needed.

I don't have a personal opinion about this but having a requirements file that installs everything makes sense.

**Comment by rochacbruno** [comment]
The problem is that we need to keep more requirements in sync and that is not nice to maintain.
This is the kind of problem that https://github.com/pypa/pipfile is coming to solve, but it is not yet ready.

Is there any other use case for this or the problem is only on Pycharm?

I used Pycharm for a while and never had that problem because I use to create virtualenvs, install things on the shell and then configuring PyCharm to use that virtualenv.

**Comment by ntkathole** [comment]
Please feel free to re-open, if this still needs fixing.
