### ISSUE TITLE
Update cli testcases where setUpClass functionality is emulated within setUp

### ISSUE THREAD

**Issue by svtkachenko** [SatelliteQE/robottelo#5085]
Some testcases have conditional setup that creates required entities when called by the first test, other tests re-using created entities. This fits the idea of setUpClass.
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_contentview.py#L151

Also it hides real problems when setup fails. For example, contentview tests failed because of manifest upload timeout prior repository was enabled, but only first one showed that error:
```
SSHCommandTimeoutError: ssh command: LANG=en_US.UTF-8  hammer -v -u admin -p changeme  subscription upload --organization-id="605" --file="/tmp/manifest-1501323746.zip"   did not respond in the predefined time (timeout=900)
```
while other tests expected enabled repository but got None because of failed setup:
```
        ContentView.add_repository({
            u'id': new_cv['id'],
            u'organization-id': ContentViewTestCase.rhel_content_org['id'],
>           u'repository-id': ContentViewTestCase.rhel_repo['id'],
        })
E       TypeError: 'NoneType' object has no attribute '__getitem__'
```

Affected testcases:
```
% grep -r 'if .*TestCase' tests/foreman --include='*.py'
tests/foreman/cli/test_contentview.py:        if ContentViewTestCase.env1 is None:
tests/foreman/cli/test_host_collection.py:        if HostCollectionTestCase.default_cv is None:
tests/foreman/cli/test_lifecycleenvironment.py:        if LifeCycleEnvironmentTestCase.org is None:
tests/foreman/cli/test_product.py:        if ProductTestCase.org is None:
tests/foreman/cli/test_repository.py:        if RepositoryTestCase.org is None:
tests/foreman/cli/test_satellitesync.py:        if not RepositoryExportTestCase.is_set_up:
tests/foreman/cli/test_syncplan.py:        if SyncPlanTestCase.org is None:
```

**Comment by swadeley** [comment]
Hello

* I have replaced the `def setUp(self)` and the series of if statements with a `def setUpClass(cls)`. 
* I have removed `env1` and `env2` variables (`env2` variable was not used anywhere).

I ran `pytest tests/foreman/cli/test_contentview.py::ContentViewTestCase`

Some tests skipped or failed because I do not have  a Capsule set up. Also no ` provisioning_server` configured.

tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_remove_cv_version_from_env_with_host_registered SKIPPED

tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_delete_cv_multi_env_promoted_with_host_registered SKIPPED

tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_remove_cv_version_from_multi_env_capsule_scenario FAILED


tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_sub_host_with_restricted_user_perm_at_default_loc FAILED
