### ISSUE TITLE
Teardown for capsule fails in tier3 and tier4

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/robottelo#6550]
Identified classes

-  tests.foreman.api.test_contentmanagement.CapsuleContentManagementTestCase 
-  tests.foreman.cli.test_capsule_installer.CapsuleInstallerTestCase
- 

The teardown doesn't occur when the test fails, this is true for tier3 and tier4 and for 6.5 and 6.4 branch.
This creates  numerous running capsule boxes on server.

**Comment by vijay8451** [comment]
@san7ket 
1. Above issue is coming because when any related testcase failed[1] during "SetUpClass" so this Capsule box does not get find during 'destroy'[2]  on Satellite(because capsule is not yet under Satellite hosts ) and same is leading here to keep that instance in run state for forever:

[1]++++++++++++++++++++++++++++++
Repository rhel7 is listed more than once in the configuration
Error: Package: pulp-selinux-2.18.0-0.1.rc.el7sat.noarch (capsule)
           Requires: selinux-policy >= 3.13.1-229.el7_6.6
           Installed: selinux-policy-3.13.1-229.el7.noarch (@anaconda/7.6)
               selinux-policy = 3.13.1-229.el7
Error: Package: foreman-selinux-1.20.0-1.el7sat.noarch (capsule)
           Requires: selinux-policy >= 3.13.1-229.el7_6.5
           Installed: selinux-policy-3.13.1-229.el7.noarch (@anaconda/7.6)
               selinux-policy = 3.13.1-229.el7

2018-12-18 17:47:53 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f38f04ad9e8
2018-12-18 17:47:53 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f38f06f27b8
2018-12-18 17:47:53 - robottelo.ssh - INFO - Connected to xx.xx.xx.xx]
2018-12-18 17:47:53 - robottelo.ssh - INFO - >>> rpm -q satellite-capsule
2018-12-18 17:47:54 - robottelo.ssh - INFO - <<< stdout
**package satellite-capsule is not installed**

2018-12-18 17:47:57 - robottelo.ssh - INFO - <<< stderr
Could not delete the host:
  **Error: host not found.**

++++++++++++++++++++++++++++++ 

[2]+++++++++++++++++++++   
def create(self):
        super(CapsuleVirtualMachine, self).create()
        try:
            self._setup_capsule()
        except Exception:
            # handle exception as VirtualMachine has no exception handling
            # in __enter__ function
            self.destroy()                                                      <<<==== here
            raise

++++++++++++

2. So worth to add exception handling for 'Could not delete the host' during destroy/(capsule_cleanup') [3].

 [3]+++++++++++++++
Under mentioned '_capsule_cleanup' :

        if self._capsule_hostname:
            # do cleanup as using a static hostname that can be reused by
            # other tests and organizations
            try:
                # try to delete the hostname first
                Host.delete({'name': self._capsule_hostname})
                # try delete the capsule
            except Exception as exp:
                # do nothing, only log the exception
                # as maybe that the host was not registered or setup does not
                # reach that stage
                # or maybe that the capsule was not registered or setup does
                # not reach that stage
                if bz_bug_is_open('1622064'):
                    logger.warn('Failed to cleanup the host: {0}\n{1}'.format(
                        self.hostname, exp))
                else:
                    logger.error('Failed to cleanup the host: {0}\n{1}'.format(
                        self.hostname, exp))
                    raise
            try:
                # try to delete the capsule if it was added already
                Capsule.delete({'name': self._capsule_hostname})
            except Exception as exp:
                logger.error('Failed to cleanup the capsule: {0}\n{1}'.format(
                    self.hostname, exp))
                raise
+++++++++++++++

**Comment by vijay8451** [comment]
PR is merged hence closing the issue.
