### ISSUE TITLE
UI: Handle sync plans error

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/robottelo#745]
As sync plans erros is not reflected on the UI due to https://bugzilla.redhat.com/show_bug.cgi?id=1087425, the sync plans errors should be handled accordingly when the blocking issue is closed on `test_positive_create_2` sync plan test.

Related to https://github.com/omaciel/robottelo/pull/730#discussion-diff-11741932

**Comment by abalakh** [comment]
As I understand, the idea is to use locator ```common_locators['name_haserror']``` instead of temporary ```common_locators["common_haserror"]``` in tests.
Issue [1087425](https://bugzilla.redhat.com/show_bug.cgi?id=1087425) is already closed, but ```name_haserror``` locator is still not applicable - labels on 'New Sync Plan' page have empty ```for``` attribute, like this:
```html
<label class="control-label col-sm-2 ng-binding" for="">Name</label>
```
For example, here's label from 'New Host' page:
```html
<label class="col-md-2 control-label" for="name">Name *</label>
```
And the ```name_haserror``` locator is looking for the label by its ```for``` attribute.
Should I create some low-priority BZ for this attribute on 'New Sync Plan' page or just bypass the issue by checking label's text, not the `for` attribute in this specific case?

**Comment by elyezer** [comment]
Please create the BZ, good catch!
