### ISSUE TITLE
hammer gpg sub-command deprecated in favour of content-credentials

### ISSUE THREAD

**Issue by swadeley** [SatelliteQE/robottelo#8018]
Hello

In Satellite 6.8, the hammer gpg sub-command is deprecated in favour of content-credentials.[1][2]

The main change is `command_base = 'content-credentials'` in `robottelo/cli/gpgkey.py `
A change is also needed in `robottelo/cli/factory.py`: The `def make_gpg_key` definition needs `'content-type': 'gpg_key'` added.

Some doc string changes in tests/foreman/cli/test_gpgkey.py are required, and I will also update text in `tests/foreman/cli/test_gpgkey.py`.

Question: Should I leave the existing gpg key test file until after we branch for 6.8, and make a new test file with the changes?
Running both old and new tests in parallel is slightly complicated by the one and only one `def make_gpg_key` definition. I would also have to make a new class to replace GPGKey(Base) class in `robottelo/cli/gpgkey.py `. 

If I don't make a new test file, I presume I do not have to change all the test UUIDs.

 [1] Fixes #28293 - rename gpg command #714
https://github.com/Katello/hammer-cli-katello/pull/714

[2]
Rename "hammer gpg" command
https://projects.theforeman.org/issues/28293

**Comment by mirekdlugosz** [comment]
When will that take effect? In satellite 6.8 or 6.9?

Is new command API compatible with old API? I mean, can you take any past `hammer gpg` command, substitute `gpg` with `content-credentials` and it will just work?

Assuming these took effect already and API is compatible:
1. For immediate solution, change command_base to route all robottelo gpg calls to new API
2. Introduce new ContentCredentials class and `make_content_credential` helper, which are basically copy of existing GPG class/helper
3. Port all existing tests from old class to new one
4. Remove old class

This approach will allow you to roll out this change gradually.

Alternative is to rename helper/class from GPG to ContentCredential and port all tests, everything in one big sweep. That will result in bigger PR and prevents you from submitting for review before actually finishing entire thing.


Overall, my main points are:
* we should try to keep robottelo API mirroring Satellite API. If hammer command is `content-credentials`, then using `robottelo.cli.gpg` would be surprising.
* not much point in keeping tests broken by design around. If `hammer gpg` command doesn't work, then what would be the value of having test that uses `hammer gpg`?

**Comment by swadeley** [comment]
> When will that take effect? In satellite 6.8 or 6.9?
> 
The gpg sub-command is depreciated in 6.8, both gpg and new content-credentials command work. 

> Is new command API compatible with old API? I mean, can you take any past `hammer gpg` command, substitute `gpg` with `content-credentials` and it will just work?
Not quite, there is new argument you need to pass, because content-credential can be a gpg key or a certificate. See example command in this cdocs bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1875714#c3
> 
> Assuming these took effect already and API is compatible:
> 
>     1. For immediate solution, change command_base to route all robottelo gpg calls to new API
I did that in PR #8019, but now I am thinking to clone the `command_base` file and rename it, so we can have both commands tested in 6.8.
> 
>     2. Introduce new ContentCredentials class and `make_content_credential` helper, which are basically copy of existing GPG class/helper
> 
>     3. Port all existing tests from old class to new one
> 
>     4. Remove old class
I am thinking now to leave that till 6.8 branch has beenmade, then do that in master, so 6,.8 branch will always have both gpg and some content-credentails tests.
> 
> 
> This approach will allow you to roll out this change gradually.
I think we should go gradual route


thank you

**Comment by swadeley** [comment]
Hello

 In Sat6.8, only the gpg_key option for content-credentials is supported.

[BZ#1884246 – [RFE] Add support for SSL certificates to hammer content-credentials](https://bugzilla.redhat.com/show_bug.cgi?id=1884246)
