### ISSUE TITLE
Wrap up API v2 framework

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#979]
This is a generic task for all the API work done by @Ichimonji10 and @elyezer. Please create small tasks as needed and link to this one.

**Comment by Ichimonji10** [comment]
The API v2 framework can still use significant improvements. For example, it would be nice to have an `EntitySearchMixin` and an `EntityUpdateMixin`, and it would be nice to have proper support for multiple API versions. However, many of those issues are being pushed over to NailGun so that they can be worked on separately. The idea is that NailGun will be able to advance at its own pace, and Robottelo will be able to take advantage of improvements as they become available.

I think we can reasonably say that the API v2 framework is "done" when module `robottelo.entities` is finally pushed over to NailGun. This means making a few changes:

- [ ] Fix all linting issues in `robottelo.entities`.
- [ ] Drop unnecessary imports from `robottelo.entities`. Any imports that cannot be dropped will have to be ported over to NailGun.

**Comment by Ichimonji10** [comment]
I've addressed #2065 and #2066 in PR #2078. When that PR is merged, I think I'll port `robottelo.entities` to NailGun, release NailGun 0.8.0, pin Robottelo to that version and address #2069. That seems like the quickest method of porting `robottelo.entities` to NailGun.

The down side of that approach is that #2067 and #2068 won't be fixed right away. However, there is great value in finally making NailGun a stand-alone package that can be installed and used. And it's expected that there will be churn in the API of a library before its 1.0 release, and until that release happens, I'll just have to make good use of versioning.

**Comment by Ichimonji10** [comment]
I'm marking this as done. More work definitely needs to be done on API tooling. However, we've come far enough that we now have a cohesive stand-alone product that is of use to anyone using Satellite's API. Remaining tasks have been moved to NailGun's issue tracker.
